export const pangrams = [
	'A mad boxer shot a quick, gloved jab to the jaw of his dizzy opponent',
	'A quart jar of oil mixed with zinc oxide makes a very bright paint',
	'All questions asked by five watched experts amaze the judge',
	'Amazingly few discotheques provide jukeboxes',
	'Anxious Al waved back his pa from the zinc quarry just sighted',
	'As we explored the gulf in Zanzibar, we quickly moved closer to the jutting rocks',
	'Back home after jiving so, he expired with quizzicality',
	'Big Fuji waves pitch enzymed kex liquor',
	'Cozy lummox gives smart squid who asks for job pen',
	'Fix problem quickly with galvanized jets',
	'Glib jocks quiz nymph to vex dwarf',
	'Grumpy wizards make toxic brew for the evil queen and jack',
	'Heavy boxes perform quick waltzes and jigs',
	'How quickly daft jumping zebras vex',
	'How razorback-jumping frogs can level six piqued gymnasts',
	'How vexingly quick daft zebras jump',
	'If I give you cloth with quartz beads (onyx, jasper, amethyst), keep it',
	'Jackdaws love my big sphinx of quartz',
	'Jaded zombies acted quaintly but kept driving their oxen forward',
	'Jinxed wizards pluck ivy from the big quilt',
	'Jived fox nymph grabs quick waltz',
	'Joe was pleased over our gift of quail, mink, zebra, and clever oryx',
	'Pack my box with five dozen liquor jugs',
	'Picking just six quinces, the new farmhand proves strong but lazy',
	'Quick zephyrs blow, vexing daft Jim',
	'Six big juicy steaks sizzled in a pan as five workmen left the quarry',
	'Sixty zippers were quickly picked from the woven jute bag',
	'Sphinx of black quartz, judge my vow',
	'The explorer was frozen in his big kayak just after making queer discoveries',
	'The five boxing wizards jump quickly',
	'The job requires extra pluck and zeal from every young wage earner',
	'The July sun caused a fragment of black pine wax to ooze on the velvet quilt',
	'The public was amazed to view the quickness and dexterity of the juggler',
	'The quick brown fox jumps over the lazy dog',
	'The soprano took Mozart’s joyful quavers with grace and exuberance',
	'The vixen jumped quickly on her foe, barking with zeal',
	'The wizard quickly jinxed the gnomes before they vaporized',
	'Traveling beneath the azure sky in our jolly ox-cart, we often hit bumps quite hard',
	'Waltz, bad nymph, for quick jigs vex',
	'We promptly judged antique ivory buckles for the next prize',
	'We quickly seized the black axle and just saved it from going past him',
	'Whenever the black fox jumped, the squirrel gazed suspiciously',
	'While making deep excavations, we found some quaint bronze jewelry',
	'William said that everything about his jacket was in quite good condition except for the zipper',
];
