name: release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

env:
  ITCH_USER: seansleblanc
  ITCH_GAME: gimme-font
  DISCORD_USERNAME: ${{ github.repository }}
  DISCORD_AVATAR: https://raw.githubusercontent.com/${{ github.repository }}/main/src/assets/icon.png

jobs:
  notify-start:
    runs-on: ubuntu-latest
    steps:
      - uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{ "color": 16426275, "title": "deploying...", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }]'

  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 21.x
          extra_plugins: |
            @semantic-release/changelog@6.x
            @semantic-release/git@10.x
          branches: main
      - id: package-version
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - uses: yeslayla/butler-publish-itchio-action@b5f0b072e8b12b731c69f12b5430f594700e0947
        if: steps.semantic.outputs.new_release_published == 'true'
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: web
          ITCH_GAME: ${{ env.ITCH_GAME }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: dist
          VERSION: ${{ steps.package-version.outputs.current-version }}

  notify-finished:
    if: ${{ success() || failure() }}
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: Ilshidur/action-discord@0.3.2
        if: ${{ success() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{ "color": 2357925, "title": "v${{ steps.package-version.outputs.current-version }} deployed", "url": "https://${{ env.ITCH_USER }}.itch.io/${{ env.ITCH_GAME }}" }]'
      - uses: Ilshidur/action-discord@0.3.2
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{ "color": 16393080, "title": "failed", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }]'
